apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "test-secret-1"
          objectType: "secretsmanager"
  secretObjects:
  - secretName: test-k8s-secret-1
    type: Opaque
    data: 
    - objectName: "test-secret-1"
      key: "test-secret-1"